package scripts_test

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestMergeWaybarConfigBuildsOneProcessSignalContract(t *testing.T) {
	dir := t.TempDir()
	top := filepath.Join(dir, "top.jsonc")
	bottom := filepath.Join(dir, "bottom.jsonc")
	output := filepath.Join(dir, "combined.jsonc")
	if err := os.WriteFile(top, []byte("// top\n[\n  {\n    \"name\": \"top\",\n    \"position\": \"top\"\n  }\n]\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile("../waybar/claude.jsonc")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(bottom, b, 0o600); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("bash", "merge-waybar-config", top, bottom, output)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("merge: %v\n%s", err, out)
	}
	merged, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	text := string(merged)
	for _, want := range []string{
		`"name": "top"`, `"on-sigusr1": "toggle"`, `"on-sigusr2": "noop"`,
		`"name": "claude"`, `"start_hidden": true`, `"on-sigusr1": "noop"`, `"on-sigusr2": "toggle"`,
		`/proc/$PPID/stat`,
	} {
		if !strings.Contains(text, want) {
			t.Errorf("combined config is missing %q", want)
		}
	}
	if got := strings.Count(text, `"name":`); got != 2 {
		t.Errorf("combined named bars = %d, want 2", got)
	}
	if got := strings.Count(text, "Generated by scripts/merge-waybar-config"); got != 1 {
		t.Errorf("generated document count = %d, want 1", got)
	}
	if cleaned := stripJSONComments(merged); !json.Valid(cleaned) {
		t.Fatal("combined output is not valid JSON after removing JSONC comments")
	}
}

func stripJSONComments(input []byte) []byte {
	out := make([]byte, 0, len(input))
	inString, escaped := false, false
	for i := 0; i < len(input); i++ {
		c := input[i]
		if inString {
			out = append(out, c)
			if escaped {
				escaped = false
			} else if c == '\\' {
				escaped = true
			} else if c == '"' {
				inString = false
			}
			continue
		}
		if c == '"' {
			inString = true
			out = append(out, c)
			continue
		}
		if c == '/' && i+1 < len(input) && input[i+1] == '/' {
			for i < len(input) && input[i] != '\n' {
				i++
			}
			out = append(out, '\n')
			continue
		}
		if c == '/' && i+1 < len(input) && input[i+1] == '*' {
			i += 2
			for i+1 < len(input) && !(input[i] == '*' && input[i+1] == '/') {
				i++
			}
			i++
			continue
		}
		out = append(out, c)
	}
	return out
}
